Refactor/your desk
MinisterioPublicoRJ/parquet-digital-web pull request #318
Opened 2021-12-28 20:51 UTC by re-andrade1987

2021-12-30 23:11 UTC, majard commented
Revisei tudo e por mim tá aprovado, só tem um erro de reload infinito mas é openCasesDetails e na minha branch já tá resolvido, vou puxar essa pra minha se quiser testar e depois abrir PR tb

2022-01-03 13:56 UTC, LaylaCsAvila requested changes

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/index.js
> +    return newState;
Outro return inútil

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/index.js
> +    setButtonList(buttons);
Outro botão que não precisa ser estado

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/index.js
> +      setLoading(false);
Seria bom matar esse estado separado e incluir o OpenCases junto com o resto dos documentos

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/index.js
> +    return { activeTab: tabName };
Return inútil

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/index.js
> +  if (loading && !buttonList) {
Se já tem um estado de loading, faz sentido ainda checar buttonList? Até porque ButtonList não precisava ser estado

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/index.jsx
> +      const { numeroMprj, numeroExterno, alertSigla, alertCount } = openCase;
Isso foi usado pra alguma coisa? Não estou achando no código

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/index.jsx
> +      if (res) newState[`${tab}Details`] = generateButtons(res.procedures);
if (res) { newState[`${tab}Details`] = generateButtons(res.procedures)};

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/index.jsx
> +    if (page < 1 || page > totalPages[activeTab]) return;
Vamos abolir o `{}` dos ifs?

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/index.jsx
>        newState[`${tabName}Details`] = null;
Qual é a função disso?

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/index.jsx
> +  }, [docs, currentPage]);
Precisa pegar openCases de novo toda vez que docs muda?

2022-01-03 13:56 UTC, LaylaCsAvila commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/styles.css
> +  left: -7vw;
Alguém sabe por que isso?

2022-01-03 15:23 UTC, majard commented on src/web/views/dashboard/sections/YourDesk/index.js
> +    return newState;
chata rs

2022-01-03 15:25 UTC, majard commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/index.jsx
> +      const { numeroMprj, numeroExterno, alertSigla, alertCount } = openCase;
Tudo de processdetail é de outra branch, a de tag de alertas, que ainda vou abrir o PR

2022-01-03 15:26 UTC, majard commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/index.jsx
> +      if (res) newState[`${tab}Details`] = generateButtons(res.procedures);
ainda fiz questão de escrever que opencasses detail tava em outra branch :/

2022-01-03 15:26 UTC, majard commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/index.jsx
> +    if (page < 1 || page > totalPages[activeTab]) return;
sim, if é coisa de burguês

2022-01-03 15:27 UTC, majard commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/index.jsx
> +  }, [docs, currentPage]);
não, vide resposta acima

2022-01-03 15:27 UTC, majard commented on src/web/views/dashboard/sections/YourDesk/openCasesDetail/styles.css
> +  left: -7vw;
aí me pegou, não faço ideia, nem lembro de ter mexido nisso rs

2022-01-07 19:42 UTC, majard commented on src/web/components/layoutPieces/ProcessDetail/index.jsx
> +
pipipi, popopó

2022-01-07 19:51 UTC, majard commented on src/web/components/layoutPieces/ProcessDetail/index.jsx
> +              const formattedAlert = individualAlertFormatter(
Não deveria ser um problema porque não tem muitos estados pra mudar, mas vou dar uma olhada com mais calma agora que vou mexer na tag de alertas

2022-01-07 19:52 UTC, majard commented on src/web/views/dashboard/sections/YourDesk/index.js
> +  if (loading && !buttonList) {
Pode ser outro tipo de loading, não o dos botões

2022-01-07 19:53 UTC, merged

2022-01-17 22:46 UTC, majard commented on src/web/views/dashboard/sections/YourDesk/index.js
> +    setButtonList(buttons);
Fiquei pensando aqui um tempão não consegui entender qual era a alternativa melhor. Criar uma variável global? Não gosto da ideia. Fazer um wrapper e passar como prop? Acho que ficaria mais complexo, desnecessariamente. Calcular logo antes do render? Mas aí teria que fazer o switch em todo rerender. Entendo que esse estado não vai mudar, mas não consegui pensar em outro jeito que não o estado cujas pros e os contras compensem. Acho que o código fica mais claro e mais seguro assim.

2022-01-17 22:47 UTC, majard commented on src/web/views/dashboard/sections/YourDesk/index.js
> +    return newState;
Vou tirar o return já que vc reclamou, mas acho que tinha algum valor semântico...